export interface Empleado {
  dui:string,
  nombre:string,
  apellido:string,
  direccion:string,
  telefono:string,
  estado:boolean,
  idDepartamento?:Number,
  salario:number,
  cargo:string,
  sexo:string,
  contrato:string,
  fechanacimiento:string,
  institucionPrevisional:string,
  correo:string,
}
export interface Empleados{
  id:string,
  nombre:string,
  apellido:string,
  correo:string,
  telefono:string,
  area:string,
  fechaContratacion:any,
  fechaCreacion:any,
  fechaModificacion:any,
  areaNavigation:any,
  ususarios:[]
}
